# /home/pjjimiso/Projects/bootdev/cloud/tmuxinator/cloud.yml

name: cloud
root: ~/Projects/bootdev/cloud

pre_window: bdshell

windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - git status
  - tubely: go run . 
  - sqlite: nix shell nixpkgs#sqlite
  - readme: vim README.md
  - cc: claude
